version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/backend.dockerfile
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/frontend.dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
